# Generated by Django 3.2.3 on 2021-07-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Carousel',
        ),
    ]
