# Generated by Django 3.2.3 on 2021-07-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0004_freature2_freature3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freature2',
        ),
        migrations.DeleteModel(
            name='Freature3',
        ),
    ]
